server:
  port: 45678
#rmq:
#  host: amqp://localhost:5672
#  username: guest
#  password: guest
#
#mp:
#  messaging:
#    connector:
#      helidon-jms:
#        named-factory: activemq
#    outgoing.emit-it:
#      connector: helidon-jms
#      destination: SomeQueue
#      type: queue
#    incoming.from-jms:
#      connector: helidon-jms
#      destination: SomeQueue
#      type: queue
#
